### ISSUE TITLE
56nF capacitor no longer available

### ISSUE THREAD

**Issue by luftpumpe83** [AK-Homberger/Satellite-Dish-Positioner#1]
The capacitor C1 (56nF) is no longer available at Reichelt. It's also hard to get anywhere else.
Is it possible to use this one instead: https://www.reichelt.de/funkentstoerkondensator-x2-56-nf-305-v-rm-10-0-105-c-10--mkp-x2-56n-p173413.html?CCOUNTRY=445&LANGUAGE=de&trstct=pos_7&nbc=1&&r=1
Thank you!

**Comment by AK-Homberger** [comment]
Hi, 
thanks for reporting the availability issue for the capacitor. Electrically your alternative would work. But it has a shorter distance between the pins (10 mm instead of 15 mm). I will try to find a a fitting alternative or I will update the PCB for your alternative capacitor with 10 mm distance.
Regards,
Andreas

**Comment by AK-Homberger** [comment]
This alternative will work with the current PCB layout: https://www.reichelt.de/de/en/radio-interference-suppression-capacitors-56nf-305v-rm15-mkp-x2-56n2-p173414.html?&nbc=1
